[package]
authors = ["Iron Fish <contact@ironfish.network> (https://ironfish.network)"]
edition = "2018"
license = "MPL-2.0"
name = "ironfish_rust"
version = "0.1.0"

[lib]
name = "ironfish_rust"
path = "src/lib.rs"

[features]
default = []
native = ["bellman/multicore", "zcash_proofs/multicore"]
wasm = []

[dependencies]
bls12_381 = "0.7"
bellman = { version = "0.13", default-features = false, features = ["groth16"]}
ff = "0.12"
group = "0.12"
jubjub = "0.9"
zcash_primitives = "0.6"
zcash_proofs = "0.6"

byteorder = "1.3.1"
lazy_static = "1.4.0"
blake2b_simd = "0.5"
blake2s_simd = "0.5"
blake3 = "1.3.0"
rand = "0.8.5"
rust-crypto-wasm = "0.3.1" # in favor of rust-crypto as this one is wasm friendly
tiny-bip39 = "0.8.0"

[patch.crates-io]
bellman = { git = "https://github.com/iron-fish/bellman", rev = "a4b2759b2421bbf47a63b129e7f78e4a61c38e64" }